pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "mvn_home"
    }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/devopstraining042024/hello-world1.git'

                // To run Maven on a Windows agent, use
                 // bat "mvn -Dmaven.test.failure.ignore=true clean package"
                bat "mvn clean verify sonar:sonar \
              -Dsonar.projectKey=helloworld \
              -Dsonar.projectName='helloworld' \
              -Dsonar.host.url=http://localhost:9000 \
              -Dsonar.token=sqp_b1baa6c0a344bd4327c3f0d54c286d0c0f0235bf"

            }
        //     post{
        //         success{
        //         archiveArtifacts artifacts: 'target/*.war'
        //         }
        //     }
            
        }
        // stage("build & SonarQube analysis") {
        //     // agent any
        //     steps {
        //       withSonarQubeEnv('sonarqube') {
        //         bat 'mvn clean package sonar:sonar'
        //       }
        //     }
        //   }
    // stage('Sonarqube') {
    // environment {
    //     scannerHome = tool 'SonarQubeScanner'
    // }
    // steps {
    //     withSonarQubeEnv('sonarqube') {
    //         // bat "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=test"
    //         bat "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=test"
    //     }
        // timeout(time: 10, unit: 'MINUTES') {
        //     waitForQualityGate abortPipeline: true
        // }
    // }
    // }
       // stage('tomcat deploy'){
       //     steps {
       //     deploy adapters: [tomcat9(credentialsId: 'tomcat_creds', path: '', url: 'http://localhost:8081/')], contextPath: null, war: 'target/*war'
       //     }
       // }
        
    }
}
